name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build the site
        run: npm run build
        env:
          VITE_PB_URL: ${{ secrets.VITE_PB_URL }}
          VITE_PB_EMAIL: ${{ secrets.VITE_PB_EMAIL }}
          VITE_PB_PASSWORD: ${{ secrets.VITE_PB_PASSWORD }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: stoned420.fun
